### ISSUE TITLE
Node.js standalone

### ISSUE THREAD

**Issue by harryd-b** [judepayne/draw-graph#1]
Would be great to have a node.js standalone.

**Comment by judepayne** [comment]
I think that's a good idea Harry and I will get it to. The current command line tool is slow because (a) JVM start up & loading Clojure and (b) it's running the transpiled-to-js version of graphviz in a not particular fast javascript engine hosted by the jvm.
I could eliminate (b) by shelling out to graphviz.
Are you able to install the graphviz binary locally?

**Comment by judepayne** [comment]
I've moved the command line tool over to java that shells out to graphviz which you must now have installed locally.

    time java -jar target/cmd-draw-graph-0.2.0-standalone.jar  \
    -p '/usr/local/bin/dot' \
    -i  '{"data":"h,animal:person\ne,pandas:huxley,pandas:bridget\ne,pandas:bridget,pandas:max",
     "display-options" : {"layout" : "dot", "label" : "person"},
     "format-in" : "csv",
     "format-out" : "svg"}'

Results in:

     <svg .....>
     etc
     etc
     </svg>

    real	0m1.868s
    user	0m4.997s
    sys	0m0.237s

How does this compare to the previous version on your system?

**Comment by harryd-b** [comment]
New Time: command took 0:0:24.39 (24.39s total)
Old Time: command took 0:0:26.34 (26.34s total)
This is running on a Windows VM with 2CPUs but still a large difference from your test times. Unclear where the bottleneck is.
Here are the cmd lines:
Old: timecmd java -jar cmd-draw-graph-0.1.0-standalone.jar  -i  "{\"data\":\"h,animal:person\ne,pandas:huxley,pandas:bridget\ne,pandas:bridget,pandas:max\", \"display-options\" : {\"layout\" : \"dot\", \"label\" : \"person\"}, \"format-in\" : \"csv\", \"format-out\" : \"svg\"}"
New: timecmd java -jar cmd-draw-graph-0.2.0-standalone.jar  -p "..\graphviz-2.38\release\bin\dot" -i  "{\"data\":\"h,animal:person\ne,pandas:huxley,pandas:bridget\ne,pandas:bridget,pandas:max\", \"display-options\" : {\"layout\" : \"dot\", \"label\": \"person\"}, \"format-in\" : \"csv\", \"format-out\" : \"svg\"}"

**Comment by harryd-b** [comment]
The first test I ran this morning didn’t show much difference between the two but subsequent tests show a massive difference. ~8 seconds with a locally installed graphviz vs ~42 seconds with the embedded version so this looks like a significant improvement in performance thanks!
p.s. Not sure why there is such a large discrepancy in overall run times but I'm running on a windows VM with 2 cpus.
